# Docker compose file to manage your deployed images.
# Use MySQL server 8 and latest Scada-LTS local build.
# Using attached webapps folder as developer you will be able to modify the static content from host os.
# Attach shell to stop the tomcat instance and then you will be able to run in JPDA mode.
services: 
    database:
        container_name: mysql
        image: mysql/mysql-server:8.0.32
        ports:
            - "0.0.0.0:3307:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=scadalts
        expose: ["3307"]
        volumes:
            - ./db_data:/var/lib/mysql:rw
            - ./db_conf:/etc/mysql:ro
        command: --log_bin_trust_function_creators=1
        networks:
            - scadalts_network

    scadalts:
        image: scadalts/scadalts:latest
        environment:
            - CATALINA_OPTS=-Xmx2G -Xms2G
        ports: 
            - "0.0.0.0:8080:8080"
        depends_on: 
            - database
        expose: ["8080", "8000"]
        volumes:
            - ./tomcat_log:/usr/local/tomcat/logs:rw
        links:
            - database:database
        command:
            - /usr/bin/wait-for-it
            - --host=database
            - --port=3306
            - --timeout=30
            - --strict
            - --
            - /usr/local/tomcat/bin/catalina.sh
            - run
        networks:
            - scadalts_network

    mqtt:
        image: hivemq/hivemq4:latest
        ports:
            - "0.0.0.0:8081:8080"
            - "1883:1883"
        expose: [ "8081", "1883" ]
        networks:
            - scadalts_network
    
    components:
        build:
            context: ./components
            dockerfile: Dockerfile
        working_dir: /components/components_startup.sh
        entrypoint: ["/bin/sh", "-c", "./components_startup.sh"]
        ports:
            - "5020:5020"  # PLC Modbus Port
            - "5000:5000"  # HMI Web Interface
            - "5001:5001"  # Actuator API
            - "5002:5002"  # Sensor API
        volumes:
            - ./components:/components/components_startup.sh
        networks:
            - scadalts_network

networks:
    scadalts_network:
        driver: bridge
